import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://bestalt.org";
  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${base}/privacy`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
    { url: `${base}/contact`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${base}/notion-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/canva-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/zapier-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/slack-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/asana-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/monday-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/airtable-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/figma-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/trello-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/evernote-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/confluence-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/jira-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/zoom-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/dropbox-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/powerpoint-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/photoshop-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/github-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/teams-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/linear-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/clickup-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/basecamp-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/intercom-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/hubspot-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/salesforce-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/zendesk-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/loom-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/wordpress-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/calendly-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/dropbox-business-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/grammarly-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/discord-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/hotjar-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/wrike-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/gitlab-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/chatgpt-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/midjourney-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/capcut-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/runway-ml-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/leonardo-ai-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/power-automate-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/google-workspace-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/google-drive-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/tableau-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/amplitude-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/pipedrive-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/mixpanel-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
  ];
}
